config/routes.rb
JiApp::Application.routes.draw do

  root :to => 'static_pages#home'

  resources :users do
    collection do
      get :show_banker
      get :show_vendor
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  
  resources :credits do 
    member do
        put :transfer
        put :payout
        put :redeem_credits
    end
  end

  resources :games do
    resources :pools do
      resources :players
    end
  end

  resources :prizes do
    member do 
      put :redeem_prize
    end
  end

  resources :addresses

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/permission', to: 'static_pages#permission'

  match '/game', to: 'static_pages#game'

 

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :last_name, :first_name, :password, :password_confirmation, :user_type, :avatar, :status, :created_at, :updated_at
  has_many :credits
  has_many :games
  has_many :pools
  has_many :players
  has_many :prizes
  has_many :addresses

  has_secure_password #Rails 3 helper method to require/encrpypt password and password confirmation using password digest

  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def self.search(search)
    if search
      where('first_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  require 'carrierwave/orm/activerecord'
    mount_uploader :avatar, AvatarUploader

  #logic

  

  private

  def create_remember_token
  	 self.remember_token = SecureRandom.urlsafe_base64
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers, :show_banker, :show_vendor]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  before_filter :banker_user,    only: :show_banker
  before_filter :vendor_user,    only: :show_vendor
  helper_method :sort_column, :sort_direction

  def index
    if admin?
    @users = User.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    #Banker Function
    @vendors = User.find_all_by_user_type(2)
    else
      redirect_to permission_path
    end
  end

  def new
    @user = User.new

  # JSON
  # render json: @user
  end
  

  def create
    @user = User.new(params[:user])
    if @user.save
       sign_in @user
       redirect_to @user
    else
       render 'new'
    end

    # JSON
    # render json: @user
  end

  def show
  	@user = User.find(params[:id])
    @player_credits = Credit.find(:all, :conditions => {:user_id => current_user.id, :pool_id => nil}).count
    @players = current_user.players
    @pool_credits = @players.sum(:bet)
    @credit_code = Credit.find_by_credit_code(:credit_code)

    # JSON
    # render json: {user: @user, player_credits: @player_credits, pool_credits: @pool_credits, credit_code: @credit_code}
    # @credit_code = input
  end

  def edit
    @user = User.find(params[:id])

    # JSON
    # render json: @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
        sign_in @user
        flash[:success] = "User Profile updated"
        redirect_to @user
    else
        render 'edit'
    end

    # JSON
    # render json: @user
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted!"
    redirect_to users_path
  end

  #Banker Account Actions:
  def show_banker
    @user = User.find(current_user)
    @total_credits = Credit.all.count
    @bankers = User.find_all_by_user_type(3)
    @credits_in_bank = Credit.find_all_by_user_id(@bankers).count
    @vendors = User.find_all_by_user_type(2)
    @credits_in_vendors = Credit.find_all_by_user_id(@vendors).count
    @players = User.find_all_by_user_type(1)
    @credits_in_players = Credit.find_all_by_user_id(@players).count
    @credits_in_pools = Credit.find_all_by_user_id(nil).count
  end

  #Vendor Account Actions:
  def show_vendor
    @user = User.find(current_user)
    @vendor_credits = Credit.find_all_by_user_id(current_user)
    @vendor_credit_count = @vendor_credits.count
    @vendor_credit_first = @vendor_credits.first
    @credit_code = @vendor_credit_first.credit_code
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

  def banker_user
    redirect_to root_path unless current_user.user_type == 3
  end

  def vendor_user
    redirect_to root_path unless current_user.user_type == 2
  end

  def sort_column
    params[:sort] || "first_name"
  end

  def sort_direction
    params[:direction] || "asc"
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
	def full_name(user)
		user.first_name + " " + user.last_name
	end

	#Check Admin

	def admin?
		current_user.user_type == 4
	end

	def banker?
		current_user.user_type == 3
	end
end

app/views/users/_user.html.erb
<li>
	<table id="user_table" class="table table-bordered">
	<tr>
        <th rowspan="2" style="width:50px; height:30px;"><%= image_tag user.avatar_url.to_s, :id => 'profile' %></th>
		<th>Name:</th>
        <th>Email:</th>
        <% if current_user.user_type == 3 %>
        <th>
            Transfer Credit
        </th>
        <% end %>
        <% if current_user.user_type == 4 && !current_user?(user) %>
        <th>Delete Account:</th>
        <% end %>
	</tr>
	<tr>
    	<th><%= link_to full_name(user), user %></th>
        <td>
            <%= user.email %>
        </td>
        <% if current_user.user_type == 3 %>
        <td>
            <%= link_to  "Transfer", transfer_credit_path(user), :method => :put %>
        </td>
        <% end %>

        <% if current_user.user_type == 4 && !current_user?(user) %>
        <td> <%= link_to "delete", user, method: :delete, data: { confirm: "you sure?" } %></td>
        <% end %>

    </tr>
    </table>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>

<h1>Edit <%= full_name(@user) %>'s Profile </h1>

<div class="row">
	<div class="span6 offset3">
	
<%= form_for(@user) do |f| %>

	<%= render 'layouts/error_messages', object: f.object %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation %>					
  <%= f.label :avatar, "Upload a Profile Picture" %>
  <%= f.file_field :avatar %>

	<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All Users</h1>
<%= form_tag users_path, :method => 'get' do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :id => nil %>
	</p>
<% end %>

<table class="table">
	<tr>
		<th><%= sortable "id" %></th>
		<th><%= sortable "email" %></th>
		<th><%= sortable "first_name" %></th>
		<th><%= sortable "last_name" %></th>
	</tr>
	<% for user in @users %>
	<tr>
		<td><%= user.id %></td>
		<td><%= user.email %></td>
		<td><%= user.first_name %></td>
		<td><%= user.last_name %></td>
	</tr>
	<% end %>
</table>
<%= will_paginate @users %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>User Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		
	
<%= form_for(@user) do |f| %>

	<%= render 'layouts/error_messages', object: f.object %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation %>
	
	<%# This is a hidden field for Student Type Account 1 %>
	<%# f.hidden_field :user_type %>

	<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, full_name(@user)) %>

<div class="row">
	<%-# User Profile Picture -%>
	<aside class="span2">
		<%= image_tag @user.avatar_url.to_s, :id => 'profile' %>
	</aside>
	<%-# User contact Information-%>
	<aside class="span4">
		<section>
			<p>
			<h1>
				<%= full_name(@user) %>
			</h1>
		    </p>

			<h4>
				Email: <%= @user.email %>
			</h4>

		    <p>
		    <h4>
				<%= link_to "Update Profile", edit_user_path %>
			</h4>
		    </p>
		</section>
	</aside>

	<aside class="span6">
		<div class="user_credits">
			<h3>
				Credit Info:
			</h3>
			<p>
				Credits in Bank:
				<%= @player_credits %>
			</p>
			<p>
				Credits in Pools:
				<%= @pool_credits %>
			</p>
		</div>
	</aside>
</div>

<div class="row">
	<aside class="span6">
		<div class="credit_redeem">
			<h3 class="redeem_label">Redeem Code Here</h3>
			<%= form_tag redeem_credits_credit_path, :method => 'put' do %>
			<p>
			<%= text_field_tag :search, params[:search], :class => 'credit_redeem_form' %>
			<%= submit_tag "Redeem", :class => 'redeem_button' %>
			</p>
			<% end %>

		</div>
	</aside>
</div>

app/views/users/show_banker.html.erb
<% if current_user.user_type == 3 %>
	<h1>This is the banker page</h1>

	<div class="row">
		<%-# User Profile Picture -%>
		<aside class="span2">
			<%= image_tag @user.avatar_url.to_s, :id => 'profile' %>
		</aside>
		<%-# User contact Information-%>
		<aside class="span4">
			<section>
				<p>
				<h1>
					<%= full_name(@user) %>
				</h1>
			    </p>

				<h4>
					Email: <%= @user.email %>
				</h4>
				
			</section>
		</aside>
	</div>

</br>

	<div class="row">
		<div class="span3">
			<div class="banker_box1">
				<h3>In Bank:</h3>
			</br>
				<h1><%= @credits_in_bank %></h1>
			</div>

			<div class="banker_box2">
				<h3>In Vendors:</h3>
			</br>
				<h1><%= @credits_in_vendors %></h1>
			</div>
		</div>

		<div class="span3">
			<div class="banker_box3">
				<h3>In Pools:</h3>
			</br>
				<h1><%= @credits_in_pools %></h1>
			</div>
			
			<div class="banker_box4">
				<h3>In Users:</h3>
			</br>
				<h1><%= @credits_in_players %></h1>
			</div>
		</div>

		<div class="span6">
			<div class="banker_box5">
				<h3>Total Credits:</h3>
			</br>
				<h1 class="total_credits"><%= @total_credits %></h1>
			</div>
		</div>
	</div>
</br>
	<div class="row">
		<div class="vendor_list">
			<h3>All Vendors</h3>
			<%= render @vendors %>
		</div>
	</div>


<% else %>

	<h1> Get the Fuck Out </h1>

<% end %>

app/views/users/show_vendor.html.erb
<% if current_user.user_type == 2 %>
	<h1>This is the Vendor page</h1>

	<div class="row">
		<%-# User Profile Picture -%>
		<aside class="span2">
			<%= image_tag @user.avatar_url.to_s, :id => 'profile' %>
		</aside>
		<%-# User contact Information-%>
		<aside class="span4">
			<section>
				<p>
				<h1>
					<%= full_name(@user) %>
				</h1>
			    </p>

				<h4>
					Email: <%= @user.email %>
				</h4>
				
			</section>
		</aside>
	</div>

</br>

	<div class="credit_code">
		<h2 class="credit_code_text">
			<%= @credit_code %>
		</h2>
	</div>

<% else %>

	<h1> Get the Fuck Out </h1>

<% end %>