config/routes.rb
JiApp::Application.routes.draw do

  root :to => 'static_pages#home'

  resources :users do
    collection do
      get :show_banker
      get :show_vendor
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  
  resources :credits do 
    member do
        put :transfer
        put :payout
        put :redeem_credits
    end
  end

  resources :games do
    resources :pools do
      resources :players
    end
  end

  resources :prizes do
    member do 
      put :redeem_prize
    end
  end

  resources :addresses

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/permission', to: 'static_pages#permission'

  match '/game', to: 'static_pages#game'

 

end

app/models/credit.rb
class Credit < ActiveRecord::Base
	attr_accessible :credit_id, :user_id, :pool_id, :credit_code, :value, :created_at, :updated_at
	belongs_to :user
	#belongs_to :pool

	validates :credit_code, presence: true, length: {minimum: 5, maximum: 5}
	
	def self.search(search)
		if search
			where('credit_code LIKE ?', "%#{search}%")
		else
			scoped
		end
	end

end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
	helper_method :sort_column, :sort_direction

	def index
		@credits = Credit.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
	end

	def new
		if banker?
			@credit = Credit.new
		else
			redirect_to permission_path
		end
	end

	def create
		@credit = Credit.new(params[:credit])
		if @credit.save
			flash[:success] = "Credit Created!"
			redirect_to credits_path
		else
			flash[:error] = "Credit Not Created!"
			redirect_to credits_path
		end
	end

	def edit
		@credit = Credit.find(params[:id])
	end

	def update
		@credit = Credit.find_by_credit_code(@credit_code)
		@credit.user_id = current_user.user_id
		if @credit.update_attributes(params[:credit])
	        flash[:success] = "Credit Info Updated!"
	        redirect_to root_path
	    else
	        render 'edit'
	    end
	end

	def show
		@credit = Credit.find(params[:id])
		@owner = User.find_by_id(@credit.user_id)
	end

	def destroy
		Credit.find(params[:id]).destroy
    	flash[:success] = "Credit Deleted!"
    	redirect_to credits_path
	end

	# Custom Actions

	def transfer
	    @user = User.find(params[:id])
	    @banker = User.find_by_user_type(3)
	    @banker_credits = Credit.find_all_by_user_id(@banker)
	    @credit = @banker_credits.first
	    @credit.user_id = @user.id
	    @credit.save
	    flash[:success] = "transfer should work"
	    redirect_to show_banker_users_path
 	end

	def payout
		@player = Player.find_by_id(params[:id])
		@pool = Pool.find_by_id(@player.pool_id)
		@game = Game.find_by_id(@pool.game_id)
		@credits = Credit.find_all_by_pool_id(@pool)
		@pay_one_credit = @credits.first
		@pay_one_credit.user_id = @player.user_id
		@pay_one_credit.pool_id = nil
		if @pay_one_credit.save
			@player.destroy
			flash[:success] = "Credit Paid Out"
			redirect_to game_pool_path(@game,@pool)
		else
			flash[:notice] = "Credit not Paid Out"
			redirect_to game_pool_path(@game,@pool)
		end
	end

	def redeem_credits
		@credits = Credit.search(params[:search])
		if @credits.exists?
		@credit_redeemed = @credits.first
		@credit_redeemed.user_id = current_user.id
		@credit_redeemed.save
		flash[:success] = "Credit Redeemed"
		redirect_to current_user
		else
		flash[:error] = "Credit code invalid"
		redirect_to current_user	
		end

		# JSON
		# render json: {credits: @credits, credit_redeemed: @credit_redeemed}
	end

	private

	def sort_column
		params[:sort] || "id"
	end

	def sort_direction
		params[:direction] || "asc"
	end
end

app/views/credits/_credit.html.erb
<table class="table table-bordered">
	<tr>
		<td>Credit Id:</td>
		<td>Owner:</td>
		<td>Code:</td>
	</tr>
	<tr>
		<td><%= link_to credit.id, credit %></td>
		<td><%= full_name(credit.user) %></td>
		<td><%= credit.credit_code %></td>
	</tr>
</table>

app/views/credits/edit.html.erb
<h1>Credit Editor</h1>

app/views/credits/index.html.erb
<h1>List of all Credits in System</h1>

<%= link_to "Create New Credit", new_credit_path %>

<%= form_tag credits_path, :method => 'get' do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :id => nil %>
	</p>
<% end %>

<table class="table">
	<tr>
		<th><%= sortable "id" %></th>
		<th><%= sortable "user_id" %></th>
		<th><%= sortable "credit_code" %></th>
	</tr>
	<% for credit in @credits %>
	<tr>
		<td><%= credit.id %></td>
		<td><%= credit.user_id %></td>
		<td><%= credit.credit_code %></td>
	</tr>
	<% end %>
</table>
<%= will_paginate @credits %>

app/views/credits/new.html.erb
<h1>Credit Creation Page</h1>

<div class="row">
	<div class="span6 offset3">
	
<%= form_for(@credit) do |f| %>

	<%= f.label :credit_code %>
	<%= f.text_field :credit_code %>

	<%= f.hidden_field :user_id, :value => current_user.id %>

	<%= f.submit "Create Credit", class: "btn btn-large btn-primary" %>

<% end %>

	</div>
</div>

app/views/credits/show.html.erb
<h1>Show Page of a specific Credit</h1>

<div class="credit">
	<div>
		<h2>Credit Id: <%= @credit.id %></h2>
	</div>
	<div>
		<h2>Owner of Credit: <%= full_name(@owner) %></h2>
	</div>
	<div>
		<h2>Credit Code: <%= @credit.credit_code %></h2>
	</div>
</div>