config/routes.rb
JiApp::Application.routes.draw do

  root :to => 'static_pages#home'

  resources :users do
    collection do
      get :show_banker
      get :show_vendor
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  
  resources :credits do 
    member do
        put :transfer
        put :payout
        put :redeem_credits
    end
  end

  resources :games do
    resources :pools do
      resources :players
    end
  end

  resources :prizes do
    member do 
      put :redeem_prize
    end
  end

  resources :addresses

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/permission', to: 'static_pages#permission'

  match '/game', to: 'static_pages#game'

 

end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li> 
		<% end %>
		</ul>
	</div> 
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<p>Join the Ji</p>
	</small>
	<nav>
		<ul>
			<li><a href="http://www.espn.com">ESPN</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
	<header class ="navbar" navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
			<%= link_to "Ji", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<% if current_user == nil %>
						<li style="margin-top:10px">
							<div class="row">
								<%= form_for(:session, url: sessions_path) do |f| %>
							<div class="span2">
								<%= f.text_field :email, :placeholder => 'Email' %>
							</div>
							<div class="span2">
								<%= f.password_field :password, :placeholder => 'Password' %>
							</div>
							<div class="span1">
								<%= f.submit "Sign in", class: "btn-primary" %>
							<% end %>
							</div>
							</div>
						</li>
						<% end %>
						<% if signed_in? %>
							<% if current_user.user_type == 1 %>
							<li><%= link_to "Profile", current_user %></li>
							<% end %>
							<% if current_user.user_type == 2 %>
							<li><%= link_to "Profile", show_vendor_users_path %></li>
							<% end %>
							<% if current_user.user_type == 3 %>
							<li><%= link_to "Profile", show_banker_users_path %></li>
							<% end %>
							<% if current_user.user_type == 4 %>
							<li><%= link_to "Profile", current_user %></li>
							<% end %>
							<li><%= link_to "Users", users_path %></li>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Account <b class="caret"></b>
								</a>
									<ul class="dropdown-menu">
											<li>
												<%= link_to "Sign out", signout_path, method: "delete" %>
											</li>
									</ul>
							</li>
						<% end %>
					</ul>
				</nav>
			</div>
		</div>
	</header>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= favicon_link_tag 'favicon.png' %>
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class ="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}" ) %>
			<% end %>
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
		<%#= debug(request) if Rails.env.development? %>
	</body>
</html>